# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.8

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/natalya/Programs/clion-2017.2.3/bin/cmake/bin/cmake

# The command to remove a file.
RM = /home/natalya/Programs/clion-2017.2.3/bin/cmake/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/natalya/Documents/os/RUDP

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/natalya/Documents/os/RUDP

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/natalya/Programs/clion-2017.2.3/bin/cmake/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/home/natalya/Programs/clion-2017.2.3/bin/cmake/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/natalya/Documents/os/RUDP/CMakeFiles /home/natalya/Documents/os/RUDP/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/natalya/Documents/os/RUDP/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named RUDP

# Build rule for target.
RUDP: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 RUDP
.PHONY : RUDP

# fast build rule for target.
RUDP/fast:
	$(MAKE) -f CMakeFiles/RUDP.dir/build.make CMakeFiles/RUDP.dir/build
.PHONY : RUDP/fast

src/Core/UDP/FakeSockets/FakeMessage.o: src/Core/UDP/FakeSockets/FakeMessage.cpp.o

.PHONY : src/Core/UDP/FakeSockets/FakeMessage.o

# target to build an object file
src/Core/UDP/FakeSockets/FakeMessage.cpp.o:
	$(MAKE) -f CMakeFiles/RUDP.dir/build.make CMakeFiles/RUDP.dir/src/Core/UDP/FakeSockets/FakeMessage.cpp.o
.PHONY : src/Core/UDP/FakeSockets/FakeMessage.cpp.o

src/Core/UDP/FakeSockets/FakeMessage.i: src/Core/UDP/FakeSockets/FakeMessage.cpp.i

.PHONY : src/Core/UDP/FakeSockets/FakeMessage.i

# target to preprocess a source file
src/Core/UDP/FakeSockets/FakeMessage.cpp.i:
	$(MAKE) -f CMakeFiles/RUDP.dir/build.make CMakeFiles/RUDP.dir/src/Core/UDP/FakeSockets/FakeMessage.cpp.i
.PHONY : src/Core/UDP/FakeSockets/FakeMessage.cpp.i

src/Core/UDP/FakeSockets/FakeMessage.s: src/Core/UDP/FakeSockets/FakeMessage.cpp.s

.PHONY : src/Core/UDP/FakeSockets/FakeMessage.s

# target to generate assembly for a file
src/Core/UDP/FakeSockets/FakeMessage.cpp.s:
	$(MAKE) -f CMakeFiles/RUDP.dir/build.make CMakeFiles/RUDP.dir/src/Core/UDP/FakeSockets/FakeMessage.cpp.s
.PHONY : src/Core/UDP/FakeSockets/FakeMessage.cpp.s

src/Core/UDP/FakeSockets/FakeNetwork.o: src/Core/UDP/FakeSockets/FakeNetwork.cpp.o

.PHONY : src/Core/UDP/FakeSockets/FakeNetwork.o

# target to build an object file
src/Core/UDP/FakeSockets/FakeNetwork.cpp.o:
	$(MAKE) -f CMakeFiles/RUDP.dir/build.make CMakeFiles/RUDP.dir/src/Core/UDP/FakeSockets/FakeNetwork.cpp.o
.PHONY : src/Core/UDP/FakeSockets/FakeNetwork.cpp.o

src/Core/UDP/FakeSockets/FakeNetwork.i: src/Core/UDP/FakeSockets/FakeNetwork.cpp.i

.PHONY : src/Core/UDP/FakeSockets/FakeNetwork.i

# target to preprocess a source file
src/Core/UDP/FakeSockets/FakeNetwork.cpp.i:
	$(MAKE) -f CMakeFiles/RUDP.dir/build.make CMakeFiles/RUDP.dir/src/Core/UDP/FakeSockets/FakeNetwork.cpp.i
.PHONY : src/Core/UDP/FakeSockets/FakeNetwork.cpp.i

src/Core/UDP/FakeSockets/FakeNetwork.s: src/Core/UDP/FakeSockets/FakeNetwork.cpp.s

.PHONY : src/Core/UDP/FakeSockets/FakeNetwork.s

# target to generate assembly for a file
src/Core/UDP/FakeSockets/FakeNetwork.cpp.s:
	$(MAKE) -f CMakeFiles/RUDP.dir/build.make CMakeFiles/RUDP.dir/src/Core/UDP/FakeSockets/FakeNetwork.cpp.s
.PHONY : src/Core/UDP/FakeSockets/FakeNetwork.cpp.s

src/Core/UDP/FakeSockets/FakeSocket.o: src/Core/UDP/FakeSockets/FakeSocket.cpp.o

.PHONY : src/Core/UDP/FakeSockets/FakeSocket.o

# target to build an object file
src/Core/UDP/FakeSockets/FakeSocket.cpp.o:
	$(MAKE) -f CMakeFiles/RUDP.dir/build.make CMakeFiles/RUDP.dir/src/Core/UDP/FakeSockets/FakeSocket.cpp.o
.PHONY : src/Core/UDP/FakeSockets/FakeSocket.cpp.o

src/Core/UDP/FakeSockets/FakeSocket.i: src/Core/UDP/FakeSockets/FakeSocket.cpp.i

.PHONY : src/Core/UDP/FakeSockets/FakeSocket.i

# target to preprocess a source file
src/Core/UDP/FakeSockets/FakeSocket.cpp.i:
	$(MAKE) -f CMakeFiles/RUDP.dir/build.make CMakeFiles/RUDP.dir/src/Core/UDP/FakeSockets/FakeSocket.cpp.i
.PHONY : src/Core/UDP/FakeSockets/FakeSocket.cpp.i

src/Core/UDP/FakeSockets/FakeSocket.s: src/Core/UDP/FakeSockets/FakeSocket.cpp.s

.PHONY : src/Core/UDP/FakeSockets/FakeSocket.s

# target to generate assembly for a file
src/Core/UDP/FakeSockets/FakeSocket.cpp.s:
	$(MAKE) -f CMakeFiles/RUDP.dir/build.make CMakeFiles/RUDP.dir/src/Core/UDP/FakeSockets/FakeSocket.cpp.s
.PHONY : src/Core/UDP/FakeSockets/FakeSocket.cpp.s

src/Core/UDP/IPTarget.o: src/Core/UDP/IPTarget.cpp.o

.PHONY : src/Core/UDP/IPTarget.o

# target to build an object file
src/Core/UDP/IPTarget.cpp.o:
	$(MAKE) -f CMakeFiles/RUDP.dir/build.make CMakeFiles/RUDP.dir/src/Core/UDP/IPTarget.cpp.o
.PHONY : src/Core/UDP/IPTarget.cpp.o

src/Core/UDP/IPTarget.i: src/Core/UDP/IPTarget.cpp.i

.PHONY : src/Core/UDP/IPTarget.i

# target to preprocess a source file
src/Core/UDP/IPTarget.cpp.i:
	$(MAKE) -f CMakeFiles/RUDP.dir/build.make CMakeFiles/RUDP.dir/src/Core/UDP/IPTarget.cpp.i
.PHONY : src/Core/UDP/IPTarget.cpp.i

src/Core/UDP/IPTarget.s: src/Core/UDP/IPTarget.cpp.s

.PHONY : src/Core/UDP/IPTarget.s

# target to generate assembly for a file
src/Core/UDP/IPTarget.cpp.s:
	$(MAKE) -f CMakeFiles/RUDP.dir/build.make CMakeFiles/RUDP.dir/src/Core/UDP/IPTarget.cpp.s
.PHONY : src/Core/UDP/IPTarget.cpp.s

src/Core/UDP/Sockets/Socket.o: src/Core/UDP/Sockets/Socket.cpp.o

.PHONY : src/Core/UDP/Sockets/Socket.o

# target to build an object file
src/Core/UDP/Sockets/Socket.cpp.o:
	$(MAKE) -f CMakeFiles/RUDP.dir/build.make CMakeFiles/RUDP.dir/src/Core/UDP/Sockets/Socket.cpp.o
.PHONY : src/Core/UDP/Sockets/Socket.cpp.o

src/Core/UDP/Sockets/Socket.i: src/Core/UDP/Sockets/Socket.cpp.i

.PHONY : src/Core/UDP/Sockets/Socket.i

# target to preprocess a source file
src/Core/UDP/Sockets/Socket.cpp.i:
	$(MAKE) -f CMakeFiles/RUDP.dir/build.make CMakeFiles/RUDP.dir/src/Core/UDP/Sockets/Socket.cpp.i
.PHONY : src/Core/UDP/Sockets/Socket.cpp.i

src/Core/UDP/Sockets/Socket.s: src/Core/UDP/Sockets/Socket.cpp.s

.PHONY : src/Core/UDP/Sockets/Socket.s

# target to generate assembly for a file
src/Core/UDP/Sockets/Socket.cpp.s:
	$(MAKE) -f CMakeFiles/RUDP.dir/build.make CMakeFiles/RUDP.dir/src/Core/UDP/Sockets/Socket.cpp.s
.PHONY : src/Core/UDP/Sockets/Socket.cpp.s

src/Messages/ReliableMessage.pb.o: src/Messages/ReliableMessage.pb.cc.o

.PHONY : src/Messages/ReliableMessage.pb.o

# target to build an object file
src/Messages/ReliableMessage.pb.cc.o:
	$(MAKE) -f CMakeFiles/RUDP.dir/build.make CMakeFiles/RUDP.dir/src/Messages/ReliableMessage.pb.cc.o
.PHONY : src/Messages/ReliableMessage.pb.cc.o

src/Messages/ReliableMessage.pb.i: src/Messages/ReliableMessage.pb.cc.i

.PHONY : src/Messages/ReliableMessage.pb.i

# target to preprocess a source file
src/Messages/ReliableMessage.pb.cc.i:
	$(MAKE) -f CMakeFiles/RUDP.dir/build.make CMakeFiles/RUDP.dir/src/Messages/ReliableMessage.pb.cc.i
.PHONY : src/Messages/ReliableMessage.pb.cc.i

src/Messages/ReliableMessage.pb.s: src/Messages/ReliableMessage.pb.cc.s

.PHONY : src/Messages/ReliableMessage.pb.s

# target to generate assembly for a file
src/Messages/ReliableMessage.pb.cc.s:
	$(MAKE) -f CMakeFiles/RUDP.dir/build.make CMakeFiles/RUDP.dir/src/Messages/ReliableMessage.pb.cc.s
.PHONY : src/Messages/ReliableMessage.pb.cc.s

src/Messages/StringMessage.pb.o: src/Messages/StringMessage.pb.cc.o

.PHONY : src/Messages/StringMessage.pb.o

# target to build an object file
src/Messages/StringMessage.pb.cc.o:
	$(MAKE) -f CMakeFiles/RUDP.dir/build.make CMakeFiles/RUDP.dir/src/Messages/StringMessage.pb.cc.o
.PHONY : src/Messages/StringMessage.pb.cc.o

src/Messages/StringMessage.pb.i: src/Messages/StringMessage.pb.cc.i

.PHONY : src/Messages/StringMessage.pb.i

# target to preprocess a source file
src/Messages/StringMessage.pb.cc.i:
	$(MAKE) -f CMakeFiles/RUDP.dir/build.make CMakeFiles/RUDP.dir/src/Messages/StringMessage.pb.cc.i
.PHONY : src/Messages/StringMessage.pb.cc.i

src/Messages/StringMessage.pb.s: src/Messages/StringMessage.pb.cc.s

.PHONY : src/Messages/StringMessage.pb.s

# target to generate assembly for a file
src/Messages/StringMessage.pb.cc.s:
	$(MAKE) -f CMakeFiles/RUDP.dir/build.make CMakeFiles/RUDP.dir/src/Messages/StringMessage.pb.cc.s
.PHONY : src/Messages/StringMessage.pb.cc.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/RUDP.dir/build.make CMakeFiles/RUDP.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/RUDP.dir/build.make CMakeFiles/RUDP.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/RUDP.dir/build.make CMakeFiles/RUDP.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... RUDP"
	@echo "... src/Core/UDP/FakeSockets/FakeMessage.o"
	@echo "... src/Core/UDP/FakeSockets/FakeMessage.i"
	@echo "... src/Core/UDP/FakeSockets/FakeMessage.s"
	@echo "... src/Core/UDP/FakeSockets/FakeNetwork.o"
	@echo "... src/Core/UDP/FakeSockets/FakeNetwork.i"
	@echo "... src/Core/UDP/FakeSockets/FakeNetwork.s"
	@echo "... src/Core/UDP/FakeSockets/FakeSocket.o"
	@echo "... src/Core/UDP/FakeSockets/FakeSocket.i"
	@echo "... src/Core/UDP/FakeSockets/FakeSocket.s"
	@echo "... src/Core/UDP/IPTarget.o"
	@echo "... src/Core/UDP/IPTarget.i"
	@echo "... src/Core/UDP/IPTarget.s"
	@echo "... src/Core/UDP/Sockets/Socket.o"
	@echo "... src/Core/UDP/Sockets/Socket.i"
	@echo "... src/Core/UDP/Sockets/Socket.s"
	@echo "... src/Messages/ReliableMessage.pb.o"
	@echo "... src/Messages/ReliableMessage.pb.i"
	@echo "... src/Messages/ReliableMessage.pb.s"
	@echo "... src/Messages/StringMessage.pb.o"
	@echo "... src/Messages/StringMessage.pb.i"
	@echo "... src/Messages/StringMessage.pb.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

